# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false

  # base de datos
  config.vm.define :db_server do |client|
    client.vm.box = "centos1706_v0.2"
    client.vm.network :private_network, ip: "192.168.56.100"
    client.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "db_server" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "mariadb-server"
    end
 end

#web 1
config.vm.define :web_server1 do |wb1|
  wb1.vm.box = "centos1706_v0.2"
  wb1.vm.network :private_network, ip: "192.168.56.101"
  wb1.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "web_server1" ]
  end
  config.vm.provision :chef_solo do |chef|
    chef.install = false
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "httpd"
    chef.add_recipe "mariadb-client"
    chef.json = {"service_name" => "WebServer1"}
  end
end

#web2
config.vm.define :web_server2 do |wb2|
  wb2.vm.box = "centos1706_v0.2"
  wb2.vm.network :private_network, ip: "192.168.56.102"
  wb2.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "web_server2" ]
  end
  config.vm.provision :chef_solo do |chef|
    chef.install = false
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "httpd"
    chef.add_recipe "mariadb-client"
    chef.json = {"service_name" => "WebServer2"}
  end
end

#balanceador
config.vm.define :load_balancer do |balancer|
  balancer.vm.box = "centos1706_v0.2"
  balancer.vm.network :private_network, ip: "192.168.56.103"
  balancer.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "load_balancer" ]
  end
  config.vm.provision :chef_solo do |chef|
    chef.install = false
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "haproxy"
    chef.json = {
      "web_servers" => [
        {"ip":"192.168.56.103"},
        {"ip":"192.168.56.104"}
       ]
    }
  end
end

end
